### PR TITLE
bidirectional a-star

### PR DESCRIPTION
**Pull request by pathway**
Basic idea is to implement bidirectional a-star, which can (or not) depending on the problem, be more efficient.  So there are two priority queues.  I thought it would be a nice addition to this package.

However:
- unlike one-directional, it is not guaranteed to find the exact optimal path.  this makes it harder to test
- it is solving some tests nicely, but I am still getting some unexpected results, still debugging

### CODE REVIEW

**Comment by pathway** [comment]
So far in preliminary tests with huge tile worlds, it does not actually seem to perform better!  So this may be just for interest sake.

**Comment by pathway** [comment]
I believe I fixed the problems.
However, one test fails under bidirectional (TestPathAroundMountain) because of a non-optimal choice that PathBidir made (this is expected).  So that test does currently fail (due to change in cost) when run under bidir.

**Comment by pathway** [comment]
It works, but it still does not perform any better than the normal version.
So I would understand if you are not interested in ever merging this PR.  Esp. if you want to keep this package small and tight.
Otoh, if you are open to adding some variations on the algorithm, I may have more to try.

**Comment by beefsack** [comment]
Hi @pathway, thanks for your contribution! I've just had a read over the MR and it's a cool implementation.

I feel that an alternate implementation like this would be great in the context of a higher level path finding library, where the consumer could plug in different path finding strategies under a unified API.

You suggested this performs similarly to the existing implementation, so unfortunately I might not merge this one in in its current state for the sake of trying to keep the surface area of the library as small as possible. But it's definitely of interest, and an implementation like this could potentially play a role under a higher level abstraction.

Thanks again!

**Comment by pathway** [comment]
No worries that makes sense.
If I did want to take a shot at a higher level library, do you think I should continue on my fork of your repo, or start again?

**Pull request closed without merging**
